# This is a potassium-standard dockerfile, compatible with Banana
# Currently we only support python3.8 and the base image defined below at the moment. If you need a different base image or python version please contact https://banana.dev/support

FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

WORKDIR /

# Install git
RUN apt-get update && \
    apt-get install -yq git build-essential espeak-ng cmake wget ca-certificates tzdata&& \
    update-ca-certificates && \
    apt-get clean && \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false && \
    rm -rf /var/lib/apt/lists/*

# Install jemalloc
RUN wget https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2 && \
    tar -xvf jemalloc-5.3.0.tar.bz2 && \
    cd jemalloc-5.3.0 && \
    ./configure && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -rf jemalloc-5.3.0* && \
    ldconfig

ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so


# Install python packages.
RUN pip3 install --upgrade pip
ADD requirements.txt requirements.txt
#RUN pip3 install -r requirements.txt
RUN pip install gunicorn --no-cache-dir && \
    pip install -r requirements.txt --no-cache-dir&& \
    rm -rf /root/.cache/pip/*

# Add your model weight files 
# (in this case we have a python script)
#ADD download.py .
RUN mkdir -p Model/acg && \
    wget https://huggingface.co/spaces/TLME/Bert-VITS-Umamusume-Genshin-HonkaiSR/resolve/main/logs/UGH/G_100000.pth -O Model/acg/G_100000.pth && \
    wget https://huggingface.co/spaces/TLME/Bert-VITS-Umamusume-Genshin-HonkaiSR/resolve/main/configs/config.json -O Model/acg/config.json

ADD . .

EXPOSE 8000

CMD python3 -u app.py
